[tool.poetry]
name = "semgrep-agent"
version = "0.1.0b1"
description = ""
authors = ["Return To Corporation <support@r2c.dev>"]
license = "Proprietary"
packages = [
	{ include = "semgrep_agent", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"
click = ">=7.1.2,<9.0.0"
sh = "^1.13.1"
boltons = ">=20.2.1,<22.0.0"
glom = "^20.8.0"
pymmh3 = "^0.0.5"
attrs = ">=20.3,<22.0"
GitPython = "^3.1.11"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
jsonschema = "^3.2.0"
types-PyYAML = "^5.4.1"

[tool.poetry.scripts]
semgrep-agent = "semgrep_agent.__main__:error_guard"

[build-system]
requires = ["poetry>=1.0.10"]
build-backend = "poetry.masonry.api"
